net: wireless: fix build not using NDO_CONFIG_SUPPORT kernel/sony/msm/drivers/net/wireless/bcmdhd/dhd_linux.c:6716:25: error: 'pub' undeclared (first use in this function)
changed in commit 832b9f5

Change-Id: I84d3c662439cc10dcb037ff82c1b2b16f71738ab
Signed-off-by: David Viteri <davidteri91@gmail.com>